language: c

matrix:
    include:
        -
            os: linux
            sudo: false
            dist: trusty
            compiler: gcc
        -
            os: linux
            sudo: false
            dist: trusty
            compiler: clang
#        -
#            os: osx
#            env: HOMEBREW_NO_AUTO_UPDATE=1
#            compiler: clang

git:
    depth: 10
script:
    - make CC=$CC PREFIX=/tmp/acki +ack

